version: '3'

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile.python.dev
    volumes:
      - media_volume:/code/media
      - bundles_volume:/code/bundles
    ports: 
      - 8000:8000
    depends_on:
      - db
      - node
  
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - bundles_volume:/code/bundles

  db:
    image: postgres:14.8-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
  media_volume:
  bundles_volume:
    