FROM python:latest
WORKDIR /code/

EXPOSE 8000

COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/

RUN python3 manage.py collectstatic --noinput
RUN python3 manage.py migrate
CMD ["gunicorn", "-b", "0.0.0.0:8000", "star_burger.wsgi:application"]
