version: '3'

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile.python.prod
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
      - bundles_volume:/code/bundles
    ports: 
      - 8000
    depends_on:
      - db
      - node
      
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - bundles_volume:/code/bundles

  db:
    image: postgres:14.8-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - web

volumes:
  postgres_data:
  media_volume:
  static_volume:
  bundles_volume: