FROM node:16.16.0
WORKDIR /code/

COPY . /code/

RUN npm ci --dev
CMD ["./node_modules/.bin/parcel", "watch", "bundles-src/index.js", "--dist-dir", "bundles", "--public-url="./""]


FROM python:latest
WORKDIR /code/

EXPOSE 8000

COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/

RUN python3 manage.py collectstatic --noinput
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
