version: '3'

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - media_volume:/code/media
    ports: 
      - 8000:8000
    depends_on:
      - db
      
  db:
    image: postgres:14.8-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
  media_volume:
    