FROM python:latest
WORKDIR /code/

EXPOSE 8000

COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/

ENTRYPOINT python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000
