# Generated by Django 3.2.15 on 2022-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20221113_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Наличными'), ('Electronically', 'Электронно')], db_index=True, default='Cash', max_length=15, verbose_name='Способ оплаты'),
        ),
    ]
