# Generated by Django 3.2.15 on 2022-11-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20221122_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Наличными'), ('Electronically', 'Электронно')], db_index=True, max_length=15, verbose_name='Способ оплаты'),
        ),
    ]
